version: "3.8"

services:
  # ===========================
  # Backend - Spring Boot
  # ===========================
  api:
    build: ./backend
    container_name: api-portal
    env_file:
      - ./backend/.env
    ports:
      - "8082:8082"
    volumes:
      - ./backend/storage:${STORAGE_PATH}
    depends_on:
      - mysql
    networks:
      - app-network

  # ===========================
  # Banco de dados - MySQL 5.7
  # ===========================
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # ===========================
  # Frontend - Angular + Nginx
  # ===========================
  frontend:
    build: ./frontend
    container_name: frontend-portal
    ports:
      - "85:80"
    depends_on:
      - api
    networks:
      - app-network

# ===========================
# Volumes e Networks
# ===========================
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge